use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(Serialize_repr, Deserialize_repr, Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum Idol {
    AmamiHaruka = 1,
    KisaragiChihaya = 2,
    HoshiiMiki = 3,
    HagiwaraYukiho = 4,
    TakatsukiYayoi = 5,
    KikuchiMakoto = 6,
    MinaseIori = 7,
    ShijouTakane = 8,
    AkidukiRitsuko = 9,
    MiuraAzusa = 10,
    HutamiAmi = 11,
    HutamiMami = 12,
    GanahaHibiki = 13,
    KasugaMirai = 14,
    MogamiShizuka = 15,
    IbukiTsubasa = 16,
    TanakaKotoha = 17,
    ShimabaraErena = 18,
    SatakeMinako = 19,
    TokoroMegumi = 20,
    TokugawaMatsuri = 21,
    HakozakiSerika = 22,
    NonoharaAkane = 23,
    MochidukiAnnna = 24,
    HandaRoko = 25,
    NanaoYuriko = 26,
    TakayamaSayoko = 27,
    MatsudaArisa = 28,
    KousakaUmi = 29,
    NakataniIku = 30,
    TenkuubashiTomoka = 31,
    EmiriSuchuaTo = 32,
    KitazawaShiho = 33,
    MaihamaAyumu = 34,
    KinoshitaHinata = 35,
    YabukiKana = 36,
    YokoyamaNao = 37,
    NikaidouChiduru = 38,
    BabaKonomi = 39,
    OogamiTamaki = 40,
    ToyokawaHuuka = 41,
    MiyaoMiya = 42,
    HukudaNoriko = 43,
    MakabeMizuki = 44,
    ShinomiyaKaren = 45,
    MomoseRio = 46,
    NagayoshiSubaru = 47,
    KitakamiReika = 48,
    SuouMomoko = 49,
    Juria = 50,
    ShiraishiTsumugi = 51,
    SakuramoriKaori = 52,
}

impl std::fmt::Display for Idol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Idol::AmamiHaruka => write!(f, "天海 春香"),
            Idol::KisaragiChihaya => write!(f, "如月 千早"),
            Idol::HoshiiMiki => write!(f, "星井 美希"),
            Idol::HagiwaraYukiho => write!(f, "萩原 雪歩"),
            Idol::TakatsukiYayoi => write!(f, "高槻 やよい"),
            Idol::KikuchiMakoto => write!(f, "菊地 真"),
            Idol::MinaseIori => write!(f, "水瀬 伊織"),
            Idol::ShijouTakane => write!(f, "四条 貴音"),
            Idol::AkidukiRitsuko => write!(f, "秋月 律子"),
            Idol::MiuraAzusa => write!(f, "三浦 あずさ"),
            Idol::HutamiAmi => write!(f, "双海 亜美"),
            Idol::HutamiMami => write!(f, "双海 真美"),
            Idol::GanahaHibiki => write!(f, "我那覇 響"),
            Idol::KasugaMirai => write!(f, "春日 未来"),
            Idol::MogamiShizuka => write!(f, "最上 静香"),
            Idol::IbukiTsubasa => write!(f, "伊吹 翼"),
            Idol::TanakaKotoha => write!(f, "田中 琴葉"),
            Idol::ShimabaraErena => write!(f, "島原 エレナ"),
            Idol::SatakeMinako => write!(f, "佐竹 美奈子"),
            Idol::TokoroMegumi => write!(f, "所 恵美"),
            Idol::TokugawaMatsuri => write!(f, "徳川 まつり"),
            Idol::HakozakiSerika => write!(f, "箱崎 星梨花"),
            Idol::NonoharaAkane => write!(f, "野々原 茜"),
            Idol::MochidukiAnnna => write!(f, "望月 杏奈"),
            Idol::HandaRoko => write!(f, "ロコ"),
            Idol::NanaoYuriko => write!(f, "七尾 百合子"),
            Idol::TakayamaSayoko => write!(f, "高山 紗代子"),
            Idol::MatsudaArisa => write!(f, "松田 亜利沙"),
            Idol::KousakaUmi => write!(f, "高坂 海美"),
            Idol::NakataniIku => write!(f, "中谷 育"),
            Idol::TenkuubashiTomoka => write!(f, "天空橋 朋花"),
            Idol::EmiriSuchuaTo => write!(f, "エミリー"),
            Idol::KitazawaShiho => write!(f, "北沢 志保"),
            Idol::MaihamaAyumu => write!(f, "舞浜 歩"),
            Idol::KinoshitaHinata => write!(f, "木下 ひなた"),
            Idol::YabukiKana => write!(f, "矢吹 可奈"),
            Idol::YokoyamaNao => write!(f, "横山 奈緒"),
            Idol::NikaidouChiduru => write!(f, "二階堂 千鶴"),
            Idol::BabaKonomi => write!(f, "馬場 このみ"),
            Idol::OogamiTamaki => write!(f, "大神 環"),
            Idol::ToyokawaHuuka => write!(f, "豊川 風花"),
            Idol::MiyaoMiya => write!(f, "宮尾 美也"),
            Idol::HukudaNoriko => write!(f, "福田 のり子"),
            Idol::MakabeMizuki => write!(f, "真壁 瑞希"),
            Idol::ShinomiyaKaren => write!(f, "篠宮 可憐"),
            Idol::MomoseRio => write!(f, "百瀬 莉緒"),
            Idol::NagayoshiSubaru => write!(f, "永吉 昴"),
            Idol::KitakamiReika => write!(f, "北上 麗花"),
            Idol::SuouMomoko => write!(f, "周防 桃子"),
            Idol::Juria => write!(f, "ジュリア"),
            Idol::ShiraishiTsumugi => write!(f, "白石 紬"),
            Idol::SakuramoriKaori => write!(f, "桜守 歌織"),
        }
    }
}
